# Generated by Django 3.1.6 on 2021-02-02 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('m', 'manager'), ('c', 'client')], max_length=15, unique=True)),
                ('name', models.CharField(max_length=40)),
                ('permissions', models.ManyToManyField(blank=True, related_name='role', to='auth.Permission')),
            ],
        ),
    ]
